### ISSUE TITLE
Event preview leading me to empty site

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#100]
I just put up the next raid training event and something strange happened:
- When clicking preview, I got to an empty page with only the headers, looking like this:
![image](https://cloud.githubusercontent.com/assets/20889890/20112211/be766eb0-a5eb-11e6-9e9d-a81727af7220.png)
When I hit the back button if my browser I was on the creation page again including the preview and all the data I entered. This is an reproducable issue for events, on shouts it works all fine.

**Comment by wwevo** [comment]
should redirect to the correct page (new or update event form) now.
Should be fixed now, reopen it if you still have trouble
