### ISSUE TITLE
Set up local development environment

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#13]
- Cloning git repository
- Check for existing WebServer integration for eclipse
-> have a local running website to work with :)

**Comment by AniOnGit** [comment]
Nearly done here!

eclipse with PHP/Javascript/HTML/CSS bundles: check
xxamp: check
local database: check
website locally working: check
git push working: check

only missing SCP server data now to be able to really update the website, then this task will be closed :)

**Comment by wwevo** [comment]
Should multiple people have the actual server data?
Could we just push it into git and update the server it from one machine only?
Just a thought, two machines with access means two ways of totally screwing up everything, instead of just one :)

**Comment by AniOnGit** [comment]
Oops, forgot to answer. Yeah, that's okay with me. Closed here.
