### ISSUE TITLE
Footer concept

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#19]
What shall be included in the footer? Impressum? Link to the GitPage? What what what?

**Comment by wwevo** [comment]
it's got a nice sentence in it now...

**Comment by Kakirtog** [comment]
Maybe a picture of guild members after a succesful mission?

**Comment by Tucura** [comment]
I would put impressum and copyright into it. Whois told me that the server is running in Germany, if i'm correct then you must have an imprint easily to find on your website.
Later we could also add links as images of e.g. the github page of the website and our youtube channel(if we have one) into the footer.

And the footer should always be at the bottom of the page.

**Comment by wwevo** [comment]
I tried to implement your footer on the bottom on the page @Tucura , it broke the mobile and tablet view :) I suppose it has to be gated somehow.

Agreed on the imprint. I suppose we are in a grey area because we do not generate any money with the site. But better be safe than sorry ^^

**Comment by wwevo** [comment]
imprint and privacy stuff implemented. so far in german only, as the site is hosted in germany and I believe we are the only country that matters in this regard.
