### ISSUE TITLE
Plan: ActionMessages

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#24]
Create a plan how to implement action messages.

**Comment by wwevo** [comment]
Still frying my brain about on HOW these shall be implemented.

Have a watcher-program spy on the website to do the job? -> make it a module
Shall all modules be altered to cater for the action messages? -> make it a core function

Most functions and actions can be extrapolated by the used url's, a hard-implementation should not be necessary. What would be the more elegant way?

*I'd like to keep 'core' as small as possible, as core shall be used for other applications as well maybe become standalone, just saying :)*

Need some input here :)

**Comment by AniOnGit** [comment]
Hmm without in detail knowing the current implementation I would imagine it somehow like this:
ActionMessage is a special kind of activity.
If I am a module, no matter which one and I want to send ActionMessages based on one of my functionalities I'd need a dependency to the ActionMessages Module. I would go for a trigger-based implementation, here a little example for User Registration case:
- User registration happens in 'user module'
- 'user module' checks if action messages module is available
- 'user module' sends 'ActionMessage' to the 'action messages' module providing the message which should be displayed (for example: 'User123' registered on the guild website - Welcome!').

ActionMessages should look different like other activities, I image them to have no header and be just a plain 'box' maybe in a slightly different color with just some text in it which is provided by the module which own the 'function' that triggered the ActionMessage. So a further requirement would be different kind of activities can also provide different layouts.

While thinking about this I am wondering if ActionMessages aren't a 'core feature' seen in every usual web portal, so maybe they could also be a core function. Then any 'check if module is available' part would not be necessary.

Wall of text ends here.

**Comment by wwevo** [comment]
I have implemented a bit of code to achieve this however, since shouts do not have a title, how should I refer to them? For events i could state the event title in the action messages, but for shouts?

Could be something like 'a comment has been posted for Ani's shout from 12.09.2016'?

**Comment by wwevo** [comment]
also, removing action messages for deleted activities has to be implemented

**Comment by wwevo** [comment]
I feel this feature can be considered implemented. Please open additional Issues for bugs, if you find any and also for feature requests, if you have any ^^
