### ISSUE TITLE
Implement ActionMessages - User Registration

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#25]
Now it's time to make the ActionMessages happen! The first implementation could be an action message in MainStream when a new user has signed up to the website :)

**Comment by wwevo** [comment]
Please test this and give feedback :) hmm, how to test? Best to get a guildie without a website account to create one ^^

**Comment by wwevo** [comment]
I feel this feature can be considered implemented. Please open additional Issues for bugs, if you find any and also for feature requests, if you have any ^^
