### ISSUE TITLE
Password change functionality

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#28]
Well, the topic tells enough, doesn't it? I want to change my password, please!

**Comment by wwevo** [comment]
Yeah, I suppose this one should have been there right from the start ^^

**Comment by wwevo** [comment]
I have implemented a password change function and view, fist glance says it works. needs testing :)
Placed it inside the profile page for now.

**Comment by AniOnGit** [comment]
Just checked it, can confirm it works! :) Well done!

**Comment by wwevo** [comment]
Glad to hear it. I consider this one closed then ^^
