### ISSUE TITLE
Retrieve account-characters per GW2 API and save them to database

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#30]
- Do DB changes if necessary
- Implement link on profile page
- implement the sync

There shouldn't be - at least in this version - a auto sync, but only when the user clicks on the link on his profile page,

**Comment by wwevo** [comment]
I would store these things in the personal settings table for now. Until we need some serious handling of this data, a serialized data-package in let's say settings->account_characters should suffice. This should be revisited when we implement functions that handle characters inventories and suchlike.

**Comment by wwevo** [comment]
Implemented a basic import. Nothing automatic as of yet, one mouse-click is required. For now there's a table in the API page, for now I'd like to collect and test functions that use the API there

**Comment by wwevo** [comment]
this is easily accessible from the profile page now
