### ISSUE TITLE
Site add function

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#34]
A new site should be easy to add via web frontend. 
Idea: An option to include it into the header menu or not?

**Comment by wwevo** [comment]
It will be fairly easy to create a Site Add function and assign it a URL, but where to put it? How to integrate this site in the Website itself? It's not like we have a Menu-Manager or anything like this :)

Is this feature needed now?

**Comment by wwevo** [comment]
Closing this for now. Please reopen it as soon as we really need to add pages on a regular basis :)
