### ISSUE TITLE
Link website user accounts with gw2 accounts

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#47]
Introduce a new settings field for gw2 account names. Multiple accounts should be possible, maybe not right from the start though.
Providing an gw2 account name would allow the site to fetch guild data with the guild-leaders api key (special rights ^^) and internally link that data to the website users, to actually have a reference which website user is which guild member.

**Comment by wwevo** [comment]
Added option to import the account name for all registered users. Api key with account scope is required. A manual settings field may follow, not sure how to authenticate it though. Api seems to be the best way to go for now.

open for suggestions.

**Comment by AniOnGit** [comment]
Just tested it, works nicely. Why should we make it a manual setting field which would require further validation? I guess creating an API key should be easy enough for everyone to use premium website services :D

**Comment by wwevo** [comment]
True. Considered closed then :)
