### ISSUE TITLE
Validate API key

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#51]
I guess a lot of ppl will - even if they have read the instructions - just use an existing API key if they have one with possibly way too much permissions -> breaking the website API import because of too many data.

To prevent this lazy ppl from failing the import we should implement a API Key check which validates that permissions fit the need and will not break anything. Maybe the user can get an Error message if he wants to import with an invalid key or stuff. Just make sure he cannot break it ;)

**Comment by wwevo** [comment]
needs testing, should be fixed though
