### ISSUE TITLE
mark promoted events

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#53]
Events get promoted in the activity-stream when they are due in less than 48 hours. As it is now, it will get pushed to the top. There should be some sort of visible marking that shows that this has happened :)

**Comment by wwevo** [comment]
They get a tiny border now, suggestions are welcome.

**Comment by wwevo** [comment]
I consider this one closed. Reopen it if you have a better idea than that border.

**Comment by AniOnGit** [comment]
I like the border, it's indeed what I imagined! :)
