### ISSUE TITLE
Give events a short description

### ISSUE THREAD

**Issue by AniOnGit** [wwevo/guildhome#55]
Currently the whole event description is taken over in activity stream. That is not supercool for events which have longer description (like my raid starter event).

Idea: Give events a field 'short description' which can be filled by event poster with 200 chars max. The description itself then could go up to 1000 chars. If short description is left blank it should be automatically filled with the 100 (?) first chars of 'long description'.

**Comment by wwevo** [comment]
For now I have implemented the 100 Character solution. a ... more link will be attached to the description.

**Comment by AniOnGit** [comment]
That is awesome! Two little questions:
1. Will shouts also be affected by this functionality?
2. Can we have a '...' after the text got cut off maybe?

**Comment by wwevo** [comment]
I can add a ... ^^
Shout are not considered currently, i felt that they should have the whole box for themselves. Perhaps we can shorten Shouts with embedded stuff like pictures and tables and whatnot?

**Comment by AniOnGit** [comment]
Noo nooo, leave the shouts please, I would not wish for shouts to be cut ;)

**Comment by wwevo** [comment]
I have fixed a small bug producing unclosed html tags and added a few dots after the summary.
Should be fixed now, reopen it if you still have trouble
