### ISSUE TITLE
Preview option

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#56]
Make a preview option available. With the support of Markdown, a preview is kinda needed.
For now i'd make a second 'submit' button that simply reloads the page and outputs the preview right above the editor.

**Comment by wwevo** [comment]
Coming to think of it, a preview checkbox might be the better solution. Less buttons, less confusion?

**Comment by wwevo** [comment]
I have implemented a checkbox-style solution for shouts. There's still some small bugs, like #5, I am working on it :)
Please test and give feedback

**Comment by AniOnGit** [comment]
It's awesome, would be even more awesome when there was a second button instead of the checkbox: [Say it loud!][Better preview before sending] :D

**Comment by wwevo** [comment]
That can be arranged. I was considering using the checkbox and then have the preview show dynamically with Javascript so the send button will always send no matter what.
 in the short term a button might be simpler to implement though.

**Comment by wwevo** [comment]
Made it a button now.
Please test this and give feedback :)
