### ISSUE TITLE
Question: Which image-hosters do you prefer?

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#57]
Which image-hosters do you prefer? So we can integrate those into our editor.

Or shall the EoL Website host her own images? Your Input is needed!

**Comment by Kakirtog** [comment]
To be honest I have no idea what you are talking about. I guess it has something to do with profile pictures and how to submit them, but I don't know more. I know there is one where you can choose a picture, upload it and then resize it, that would be perfect I think.

**Comment by AniOnGit** [comment]
I only know http://imgur.com/ as a real image hoster which I already used. I just found out it even has a real API (https://api.imgur.com/) so maybe there could be a flawless integration established :)

**Comment by wwevo** [comment]
It is meant for profile pictures as well as identity pictures and Screenshots for activities, galleries and suchlike. Imgur seems nice. Have to take a look at the api :-)

**Comment by wwevo** [comment]
Since imgur is the only hoster mentioned here we will integrate imgur as the preferred and, for the time being, only image hoster available on EoL.

I consider this Issue closed, reopen it if you disagree :)
