### ISSUE TITLE
Class selection

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#67]
I have implemented a class selection template. You can add classes and assign them to events.
This is an early draft to see if this goes in the right direction. You can play around with the thing, it should not affect any other functions as of now. 

Is this a viable way to create the needed-classes list? please test and give feedback. and remember, we are talking basic functions here.

**Comment by wwevo** [comment]
As I received no feedback at all, I suppose you are all fine with my proposed solution?

**Comment by Kakirtog** [comment]
I think on top of needed classes we also need selectable roles. Like tank, healer, maybe a couple more. I think that should be custom instead of a list.

**Comment by Kakirtog** [comment]
Yes, this is a good implementation.

**Comment by wwevo** [comment]
looks like this is gonna get the boot, with the new idea of using tags. Events 1.0 will have to live without role-selection ^^
