### ISSUE TITLE
New Style for events in Activity stream

### ISSUE THREAD

**Issue by wwevo** [wwevo/guildhome#71]
We seriously need a better design for the display of events in the activity stream. Data should be presented in a much more organized fashion.

There should be a clear separation between the description, the member who posted it and data like that and the event metadata like the date and signups.

**Comment by Kakirtog** [comment]
Ok, I edited something together very very professionaly, I hope you like it: http://imgur.com/a/amtwF

**Comment by AniOnGit** [comment]
I like it! Maybe the big text one size smaller and I would have a blank line between the text and the signup button I guess, but totally like it. Well done! :)

**Comment by wwevo** [comment]
Looks good. I will look into it as soon as we take a break from the newly released Civ VI :-)

**Comment by Kakirtog** [comment]
It was meant as a rough draft, but I'm glad you like it  ^^

**Comment by wwevo** [comment]
I tinkered a bit with the event view and introduced a prototype button ^^

Does this look nice or what?

**Comment by wwevo** [comment]
I feel this feature can be considered implemented. Please open additional Issues for bugs, if you find any and also for feature requests, if you have any ^^
