### ISSUE TITLE
A separate page for special events

### ISSUE THREAD

**Issue by Kakirtog** [wwevo/guildhome#80]
Special events like Find my location or Guild hall treasure hunt don;t have a place atm. I think these would pull a lot of activity to the website. However, they can;t be set up as normal events (as there is no date), and if they're run as shouts or announcements it will clog up the rest of the website. Necro suggested a separate page for an overview of these. I think they should basically be shouts that have their own page instead of being actual shouts (if you get what I mean).

**Comment by AniOnGit** [comment]
How about making it a new activity: games? I think a FindMyLocation is more than a shout. It could have a resolved or open status, maybe a time limit, a price for one or more winners. 
New activity would also mean its own 'Games' filter. Please no more stickies, with the featured events its already enough what's pinned to the top of the page.

**Comment by wwevo** [comment]
I have been thinking about our much loved special events as well, especially find my location. With the new maps and content it's even more of a challenge. A 'Special Event Activity' with it's own landing page sounds sensible to me, for most of them it would just be like a fancy shout with fancy comments. They could get something like a 'sticky' posted on top of the stream. Perhaps even just small icons showing that any of those special events is currently active?

Perhaps there could be an entire area above the stream reserved for current stuff? Pulled events might get a compact view, perhaps several of them next to each other instead of simply being on top of the stream with a box like it is now.

```
Header
------------
activity_menu
-----------
current stuff, not bigger in area than the activity_menu above it
-----------
activity stream
-----------
Footer
```

**Comment by Kakirtog** [comment]
I think a current stuff area would be a great idea! It'd have to be more compact than the sticky events we have now, just a title and a date maybe, maybe the poster/creator? No more than that though, it should be quite compact. That would make the whole 10 days of EoL much less bloated and clearer.

I think 1 line per current/soon upcoming event is enough. There may not be many now, but say we take it about 4 days ahead, and it's friday afternoon. We have a more active website. There's a raid training on friday, missions saturday, GW1 sunday, a find my location event active, a treasure hunt in the guild hall and some introductory fractal event. That's 6 already. It won't happen soon, and it might not happen often, but it could happen and we should make sure it's not gonna be a hindrance to the rest of the website if shouts ever become popular.

**Comment by wwevo** [comment]
How about a side scrolling 'gallery' or carousel with small boxes for each event with only the date and title, and you could hover to see more info and click to get to the event page? Something like that?

**Comment by Kakirtog** [comment]
Hmm, I think that would make stuff less clear. I'd rather have a limited amount of current events show than have them sidescrolling. Presenting them next to eachother instead of from the top downwards might be a good idea though.

**Comment by AniOnGit** [comment]
![eol](https://cloud.githubusercontent.com/assets/20889890/19775876/41b23512-9c72-11e6-8414-5d81a4a0de11.jpg)

A quick draw, don't laugh ;) How about having a header area in the activity stream in a tile layout display the number of shouts/events/polls/game/whatever we want in a modern style with a big number :D 
Each section acts like a filter when clicking on it, like showing only shouts in the activity stream when you click the shouts tile.

Just a raw idea, still some stuff to think through. I would drop the current '10 Days of Eol', Shouts(+), Events(+) bar for that, but don't have a good idea how to create new activities then yet.
Also, show the numbers for last 10 days, current week, overall or or or?

**Comment by wwevo** [comment]
we could integrate new stuff (and manage old stuff) like this : 
![photo_2016-10-27_18-28-53](https://cloud.githubusercontent.com/assets/18307732/19776263/ac2d0e66-9c73-11e6-90e1-7a2ec06df920.jpg)

**Comment by wwevo** [comment]
I'll put this into the website Styled Milestone

**Comment by wwevo** [comment]
We'll take the silence as 'We love your drawings and excellent ideas, they are perfect, please implement asap'

**Comment by wwevo** [comment]
a problem with the pic would be: we'd either need several pics, or one that can easily be cropped to allow for page-size-reduction. Or we can just show the pic in desktop mode and leave it out in tablet and mobile view. (just noticed the 'beautiful pic note' in the header there :)

**Comment by Kakirtog** [comment]
Sorry for the late response, I needed some time to think about it. Also, I am lazy.

I think I like Ani's sketch best (sorry Evo). I do wonder what the numbers represent though. Is it active stuff? Stuff that was commented on or was created in the last 10 days? Is this the same for each different type? If I click on it, will I get taken to a page with just those 10shouts/3games/1poll etc.? Can we find the older stuff somewhere? How can I get back to the general activity (recent stuff)? Do we need a page or box telling us about new users, or is a notification enough? Would we email a notification about this?

**Comment by wwevo** [comment]
That's what my sketch was for... Mine was an addition to Anis, to allow for
older posts and whatnot. I in fact copied that area of Anis sketch exactly
and then added the drop down menu. The numbers should indicate the number
of polls /events etc in the last ten days. You'd be taken to the general
polls events etc pages after clicking

Am 29.10.2016 15:31 schrieb "Kakirtog" <notifications@github.com>:

**Comment by AniOnGit** [comment]
Kakir, no offense, but please read carefully again what we wrote to the pictures, I guess than can make things a bit clearer ;)
If there are still misunderstandings I might need to write a bit more to the drawing.

**Comment by Kakirtog** [comment]
Personally, I'm no fan of drop-down/fold-out menu's. I'd instead put a little 'Create New' in the top bar with Activity Stream (on the right-side). Then you'd have to select an event/stuff type before creating the rest of the event. Or, if I misunderstood your suggestion, you could make the 10 Events block it change to the 'Older/Manage/Add' menu on mouseover (same for every other type of course). That would be better than a dropdown/fouldout imo.

You can ignore my If I click on it... question in the last comment, but the rest do need an answer I think. Allow me to elaborate:
**I do wonder what the numbers represent though. Is it active stuff? Stuff that was commented on or was created in the last 10 days?**
Do these numbers represent what is on the recent activity page, like how there are all the shouts and events that were created in the last 10 days there (I'm not counting the sticky stuff for now)? Is it just created stuff or also what was recently commented on?
**Is this the same for each different type?**
Do we get the same time window of created stuff for each type? Do games get a larger window perhaps?
**Can we find older stuff somewhere?**
I suppose this has been answered without words, but I'd still like confirmation; When we click on the Polls section, so we get to a page displaying all Polls ever created (with pagination)? I do assume we keep the Recent Stuff, is that accurate too?
**How can I get back to the general activity (recent stuff)?**
Simply by clicking on the Activity Stream button?
**Do we need a page or box telling us about new users, or is a notification enough? Would we email a notification about this?**
I think a notification is enough tbh. Email I'm not sure about. Probably not for everyone.

If this needs more clarification or something, please tell me.

**Comment by AniOnGit** [comment]
Okay, the reason I wanted you to reread, was because this section in my post somehow states that I do not have an answer for that yet:
> Just a raw idea, still some stuff to think through. I would drop the current '10 Days of Eol', Shouts(+), Events(+) bar for that, but don't have a good idea how to create new activities then yet.
Also, show the numbers for last 10 days, current week, overall or or or?

Thinking about it now, I would suggest these answers:
- Numbers definetely should match with the activity stream, so if we keep display the last 10 days in activity stream, then numbers should represent that amount. 
- Yes it is the same for each activity type, it just is an indicator about how many **new** activities of each type were created the last x days.
- Older stuff is found by clicking on the activity type tile, which already got written - **with** words ;) - in the explanations to my picture. A click on an activity type tile will show all activities of the chose type.
- Back to main stream, I'd say a click on Activity Stream header may suffice.
- Dunno how this question came up, the types on my drawing where only suggestions. I'd think it could be nice to see how many users registered the last two days, maybe we wanna make it more 'valuable' info with changing that to how many users were active on the website in the last 10 days? I'd never want an email information about that (different topic also ;)).

**Comment by wwevo** [comment]
which still leaves us with the question how we are going to present current events. yesterday was a pain, three active events taking up the entire screen space and then some

**Comment by wwevo** [comment]
maybe have little icons in those numbered tiles, one icon per active event? you can hover those icons then to get a gist or click on it it visit the event page?
we should be able to fit like 4 or five in there ^^

**Comment by wwevo** [comment]
i've been playing around with these ideas. check it out on the website and tell me what you think

**Comment by Kakirtog** [comment]
Looks good!

**Comment by wwevo** [comment]
I feel this feature can be considered implemented. Please open additional Issues for bugs, if you find any and also for feature requests, if you have any ^^
