### ISSUE TITLE
A TS3 plugin/link

### ISSUE THREAD

**Issue by Kakirtog** [wwevo/guildhome#81]
Ari suggested a TS3 link where you click on it and it opens TS3 with the channel data and password loaded, so you don't have to type anything. I think that's a bit sparse on usefulness, since you really only have to type it once, and then bookmark it, but maybe it has a use, I guess it won;t take up much space (though I'm not sure where we should put that). I did have another idea about TS functionality, and that's a plugin which shows the server state, specifically whether someone is in a channel. That way you can see if there's someone to talk to, and you get a bit more use out of a TS thing. Ari commented that that was maybe not necessary with our server population, where he has a point.

**Comment by wwevo** [comment]
Well, for logged in users, who need to have that special voucher, we could simply put that TS3 link in the sidebar. How is such a link constructed?
Implementing a ts3 status should also pose no problem since it runs on the same server.

**Comment by Kakirtog** [comment]
Not sure, I'd have to ask if Ari knows.

**Comment by Tucura** [comment]
The FAQ of TS3 has an example how to link the TS3 on a html site. [Check this out](https://support.teamspeakusa.com/index.php?/Knowledgebase/Article/View/46/0/how-can-i-link-to-my-teamspeak-3-server-on-my-webpage)

I guess this one should do it for our purpose. We have to add the password parameter because the server password protected. But just people which are logged it should be able to see the link because it is easy to get the password from it.
`<a href="ts3server://ts3.hoster.com?port=9987&password=serverPassword">Click to connect to my server</a>`

**Comment by wwevo** [comment]
not on my computer ^^ ts3server:// is not known and starts a google search... I do have the latest Ts3 installed

**Comment by Kakirtog** [comment]
on this other website they had this link, which is very similar to the one Tuc mentioned:
ts3server://ts.guildoftweakers.org?port=18726

**Comment by Tucura** [comment]
I just tested it with 
`<a href="ts3server://ts3.aniware.de?port=9987&password=XXXXXXXX">Awesome EOL Server</a>` 
and it brings up the dialog where i can choose to open ts3. So it works like intended. And it opens the TS3 App and trys to connect to the server.

Sorry my browser is in german but i guess you get the idea.
![ts3starter](https://cloud.githubusercontent.com/assets/11677107/19763528/b8b9df68-9c3e-11e6-828b-6ec61d18894b.png)

So it has to be a problem on your machine Evo.

However this means we could add this onto the website:)

**Comment by wwevo** [comment]
I tested it in the browser address bar. Seems like you have to actually click a link ;-)

**Comment by Tucura** [comment]
It also works for me if i put the link into the adress bar:)

**Comment by wwevo** [comment]
A browser issue then? Which browser do you use?

**Comment by Tucura** [comment]
Firefox 49.0.2

@Kakirtog @AniOnGit Can you bot test it too? Just paste the link into your adress bar: 
`ts3server://ts3.aniware.de?port=9987&password=XXXXXXXX`

**Comment by Kakirtog** [comment]
Works in Chrome!

**Comment by wwevo** [comment]
Can one also set a user in that link? We could then use the username as ts name also. It should be relatively ready to show if a website user is currently on ts an perhaps show it on the website. Gated behind a setting if that is wanted, of course.

**Comment by AniOnGit** [comment]
That link still starts a google search for me (pasted directly to adressbar).

**Comment by wwevo** [comment]
yeah, it does that for me as well when I paste it into the addressbar. Tested only in Chrome.  
I didn't know other browsers are still used  :P

**Comment by wwevo** [comment]
[awesome ts3](ts3server://ts3.hoster.com?port=9987&password=serverPassword)

**Comment by wwevo** [comment]
I just threw the link in there now, appears only when logged in. 
I feel this feature can be considered implemented. Please open additional Issues for bugs, if you find any and also for feature requests, if you have any ^^
